export const mapConfig = {
    imageWidth: 79744,
    imageHeight: 89984,
    rate: 4,
    leftTopX: 1023,
    leftTopZ: -16865,
    minZoom: 2.6,
    maxZoom: 12,
    minNativeZoom: 4,
    initViewZoom: 3.5,
    initViewLngLat: [9000.0, 15000.0],
} as const;

export const TILE_URL = "https://pub-051657fe55414cbea2688a0d4c5ecd76.r2.dev/{z}/{x}/{y}.png";
// export const TILE_URL = "/tiles/{z}/{x}/{y}.png";

export const STATIONS_PANE = "stationsPane";
export const COMMON_LINES_PANE = "commonLinesPane";
export const CONTACT_LINES_PANE = "contactLinesPane";
export const ROUTE_PANE = "routePane";
export const MAP_PANES = [STATIONS_PANE, COMMON_LINES_PANE, CONTACT_LINES_PANE];

export const STATION_MARKER_OPTIONS = {
    radius: 6.5,
    weight: 1.2,
    color: '#000000',
    fillColor: '#ffffff',
    fillOpacity: 0.9,
}

export const CONTACT_LINE_OPTIONS = {
    color: '#a9a9a9',
    weight: 3,
    lineJoin: 'round',
}

export const COMMON_LINE_OPTIONS = {
    weight: 3.5,
    lineJoin: 'round',
}

export const GEOJSON_FILES = [
    "ac_内环方向.geojson",
    "ac_外环方向.geojson",
    "ap_世界边缘山脉方向.geojson",
    "ap_黄昏岛方向.geojson",
    "av_冰封港方向.geojson",
    "av_新赫洛堡方向.geojson",
    "bifdu2lpu_.geojson",
    "bilpd2fdd_.geojson",
    "bi_碧玺岛方向.geojson",
    "bi_鹅城方向.geojson",
    "bl_碧玺岛方向.geojson",
    "bl_鹅城方向.geojson",
    "bt_世界边缘山脉方向.geojson",
    "bt_黄昏岛方向.geojson",
    "bw_世界边缘山脉方向.geojson",
    "bw_黄昏岛方向.geojson",
    "ce2_碧玺岛方向.geojson",
    "ce2_鹅城方向.geojson",
    "celpd2fdd_.geojson",
    "ce_内环方向.geojson",
    "ce_外环方向.geojson",
    "cf_世界边缘山脉方向.geojson",
    "cf_黄昏岛方向.geojson",
    "cm_冰封港方向.geojson",
    "cm_新赫洛堡方向.geojson",
    "dcp_内环方向.geojson",
    "dcp_外环方向.geojson",
    "df2_匕首半岛方向.geojson",
    "df2_巨龙峡湾东方向.geojson",
    "dfe2_巨龙峡湾东方向.geojson",
    "dfe2_风雪峡湾方向.geojson",
    "dfe_匕首半岛方向.geojson",
    "dfe_巨龙峡湾东方向.geojson",
    "dflpd2pmd_.geojson",
    "dfpmu2lpu_.geojson",
    "df_内环方向.geojson",
    "df_外环方向.geojson",
    "dji_大绿龙岛方向.geojson",
    "dji_碧玺岛方向.geojson",
    "do_碧玺岛方向.geojson",
    "do_鹅城方向.geojson",
    "dp2_匕首半岛方向.geojson",
    "dp2_巨龙峡湾东方向.geojson",
    "dp_内环方向.geojson",
    "dp_外环方向.geojson",
    "ef1_内环方向.geojson",
    "ef1_外环方向.geojson",
    "ef2_世界边缘山脉方向.geojson",
    "ef2_黄昏岛方向.geojson",
    "eflp2pl_.geojson",
    "efpl2lp_.geojson",
    "ei_内环方向.geojson",
    "ei_外环方向.geojson",
    "em2_巨龙峡湾东方向.geojson",
    "em2_风雪峡湾方向.geojson",
    "emjdd2pmu_.geojson",
    "empmd2jdu_.geojson",
    "em_世界边缘山脉方向.geojson",
    "em_黄昏岛方向.geojson",
    "eo1_内环方向.geojson",
    "eo1_外环方向.geojson",
    "eo2_东海望方向.geojson",
    "eo2_诺亚方向.geojson",
    "eolpu2mdu_.geojson",
    "esd_巨龙峡湾东方向.geojson",
    "esd_风雪峡湾方向.geojson",
    "evpld2plzd_.geojson",
    "evplu2plzd_.geojson",
    "ev_世界边缘山脉方向.geojson",
    "ev_黄昏岛方向.geojson",
    "ew_冰封港方向.geojson",
    "ew_新赫洛堡方向.geojson",
    "fcl_世界边缘山脉方向.geojson",
    "fcl_黄昏岛方向.geojson",
    "fdz2d_碧玺岛方向.geojson",
    "ff_内环方向.geojson",
    "ff_外环方向.geojson",
    "fh2_巨龙峡湾东方向.geojson",
    "fh2_风雪峡湾方向.geojson",
    "fhhmd2jdu_.geojson",
    "fhjdd2hmu_.geojson",
    "fh_冰封港方向.geojson",
    "fh_新赫洛堡方向.geojson",
    "fp1_碧玺岛方向.geojson",
    "fp1_鹅城方向.geojson",
    "fp2_世界边缘山脉方向.geojson",
    "fp2_黄昏岛方向.geojson",
    "fpfdd2pld_.geojson",
    "fpndf2pl_.geojson",
    "fpnpl2df_.geojson",
    "fpn_世界边缘山脉方向.geojson",
    "fpn_黄昏岛方向.geojson",
    "fpplu2fdu_.geojson",
    "fpw_碧玺岛方向.geojson",
    "fpw_鹅城方向.geojson",
    "fv1_内环方向.geojson",
    "fv1_外环方向.geojson",
    "fv2_冰封港方向.geojson",
    "fv2_新赫洛堡方向.geojson",
    "fvhmd2lpu_.geojson",
    "fvlpd2hmu_.geojson",
    "ggilp2dfz_碧玺岛方向.geojson",
    "ggi_内环方向.geojson",
    "ggi_外环方向.geojson",
    "gp_冰封港方向.geojson",
    "gp_新赫洛堡方向.geojson",
    "gv_匕首半岛方向.geojson",
    "gv_巨龙峡湾东方向.geojson",
    "kbzx_结束乐队度假岛方向.geojson",
    "kri_结束乐队度假岛方向.geojson",
    "kri_结束乐队开发区方向.geojson",
    "kz_碧玺岛方向.geojson",
    "kz_鹅城方向.geojson",
    "li_内环方向.geojson",
    "li_外环方向.geojson",
    "mv_东海望方向.geojson",
    "mv_诺亚方向.geojson",
    "nf_巨龙峡湾东方向.geojson",
    "nf_风雪峡湾方向.geojson",
    "nh2_冰封港方向.geojson",
    "nh2_新赫洛堡方向.geojson",
    "nh_内环方向.geojson",
    "nh_外环方向.geojson",
    "no2_东海望方向.geojson",
    "no2_诺亚方向.geojson",
    "nolpd2mdd_.geojson",
    "no_内环方向.geojson",
    "no_外环方向.geojson",
    "nt2_东海望方向.geojson",
    "nt2_诺亚方向.geojson",
    "nt3_匕首半岛方向.geojson",
    "nt3_巨龙峡湾东方向.geojson",
    "ntmdd2pld_.geojson",
    "ntmdd2plu_.geojson",
    "ntmdd2pmd_.geojson",
    "ntmdd2pmu_.geojson",
    "ntmdu2pld_.geojson",
    "ntmdu2pmu_.geojson",
    "ntmdupmu2mdu_.geojson",
    "ntpld2mdupmu_.geojson",
    "ntpld2mdu_.geojson",
    "ntplu2mdd_.geojson",
    "ntpmd2mdd_.geojson",
    "ntpmd2mdu_.geojson",
    "ntpmd2pld_.geojson",
    "ntpmu2mdu_.geojson",
    "nt_世界边缘山脉方向.geojson",
    "nt_黄昏岛方向.geojson",
    "pld2plz_.geojson",
    "pp_内环方向.geojson",
    "pp_外环方向.geojson",
    "rb2_大绿龙岛方向.geojson",
    "rb3_龙爪半岛方向.geojson",
    "rbfdu2fdzu1_.geojson",
    "rbfdu2fdzu2_龙爪半岛方向.geojson",
    "rbfdzd2fdd_碧玺岛方向.geojson",
    "rbfdzu2kbzxu_.geojson",
    "rbkbzxd2fdzd_.geojson",
    "rb_碧玺岛方向.geojson",
    "rb_鹅城方向.geojson",
    "rh_匕首半岛方向.geojson",
    "rh_巨龙峡湾东方向.geojson",
    "rr_世界边缘山脉方向.geojson",
    "rr_黄昏岛方向.geojson",
    "rv2_黄昏岛方向.geojson",
    "rv_世界边缘山脉方向.geojson",
    "rv_贸易海岸方向.geojson",
    "sb2_冰封港方向.geojson",
    "sb2_新赫洛堡方向.geojson",
    "sb3_匕首半岛方向.geojson",
    "sb3_巨龙峡湾东方向.geojson",
    "sbdf2hm_.geojson",
    "sbdf2shlp_.geojson",
    "sbfdu2hmd_.geojson",
    "sbhm2df_.geojson",
    "sbhm2shlp_.geojson",
    "sbhmd2pmd_.geojson",
    "sbhmu2fdd_.geojson",
    "sbpmu2hmu_.geojson",
    "sb_碧玺岛方向.geojson",
    "sb_鹅城方向.geojson",
    "scv_内环方向.geojson",
    "scv_外环方向.geojson",
    "sc_匕首半岛方向.geojson",
    "sc_巨龙峡湾东方向.geojson",
    "sf2_巨龙峡湾东方向.geojson",
    "sf2_风雪峡湾方向.geojson",
    "sfb_东海望方向.geojson",
    "sfb_诺亚方向.geojson",
    "sff_世界边缘山脉方向.geojson",
    "sff_黄昏岛方向.geojson",
    "sf_内环方向.geojson",
    "sf_外环方向.geojson",
    "si_内环方向.geojson",
    "si_外环方向.geojson",
    "spi_冰封港方向.geojson",
    "spi_新赫洛堡方向.geojson",
    "sp_东海望方向.geojson",
    "sp_诺亚方向.geojson",
    "sti_冰封港方向.geojson",
    "sti_新赫洛堡方向.geojson",
    "sv_内环方向.geojson",
    "sv_外环方向.geojson",
    "swff_匕首半岛方向.geojson",
    "swff_巨龙峡湾东方向.geojson",
    "swf_匕首半岛方向.geojson",
    "swf_巨龙峡湾东方向.geojson",
    "sw_匕首半岛方向.geojson",
    "sw_巨龙峡湾东方向.geojson",
    "tc2_世界边缘山脉方向.geojson",
    "tc2_贸易海岸方向.geojson",
    "tclpu2plz_.geojson",
    "tcplz2lpd_.geojson",
    "tc_内环方向.geojson",
    "tc_外环方向.geojson",
    "th_匕首半岛方向.geojson",
    "th_巨龙峡湾东方向.geojson",
    "ti2_世界边缘山脉方向.geojson",
    "ti2_黄昏岛方向.geojson",
    "tilpd2pld_.geojson",
    "ti_内环方向.geojson",
    "ti_外环方向.geojson",
    "tsr_碧玺岛方向.geojson",
    "tsr_龙爪半岛方向.geojson",
    "tw_东海望方向.geojson",
    "tw_诺亚方向.geojson",
    "vr_内环方向.geojson",
    "vr_外环方向.geojson",
    "wp_内环方向.geojson",
    "wp_外环方向.geojson",
    "wsd_巨龙峡湾东方向.geojson",
    "wsd_风雪峡湾方向.geojson",
    "wsv1_冰封港方向.geojson",
    "wsv1_新赫洛堡方向.geojson",
    "wsv2_东海望方向.geojson",
    "wsv2_诺亚方向.geojson",
    "wsvhm2md_.geojson",
    "wsvhmd2mdu_.geojson",
    "wsvhmu2mdd_.geojson",
    "wsvmd2hm_.geojson",
    "wsvmdd2hmu_.geojson",
    "wsvmdu2hmd_.geojson",
    "wv_碧玺岛方向.geojson",
    "wv_鹅城方向.geojson",
    "xzw_内环方向.geojson",
    "xzw_外环方向.geojson",
    "yp1_内环方向.geojson",
    "yp1_外环方向.geojson",
    "yp2_碧玺岛方向.geojson",
    "yp2_鹅城方向.geojson",
    "ypdf2lp_.geojson",
    "ypfdd2lpu_.geojson",
    "yplp2df_.geojson",
    "yplpd2fdu_.geojson",
] as const;
